---
title: "UCB CS285: <tag style='font-weight: bold'>Deep Reinforcement Learning</tag>"
---


This is a collection of notes and code for the [UCB CS285: Deep Reinforcement Learning](https://rail.eecs.berkeley.edu/deeprlcourse/) course. The course covers various topics in reinforcement learning, including **policy gradients**, **actor-critic methods**, **deep Q-learning**, and **different exploration strategies**. The course is designed to provide a comprehensive understanding of deep reinforcement learning and its applications.

There are total <tag style='color: orange'>23 lectures</tag> and <tag style='color: orange'>5 assignments</tag> in this course. It might 100 hours to finish the course, including the lectures and assignments. 

##  Lectures
### Lecture 01: Introduction & Overview 
Lecture 01 introduces the course and provides an overview of reinforcement learning. It covers the basic concepts of reinforcement learning, including the agent-environment interaction, rewards, and policies. The lecture also discusses the different types of reinforcement learning algorithms, such as model-free and model-based methods.

The difference between Reinforcement Learning and Supervised Learning Algorithms is that: *Reinforcement Learning not just trying to copy everything from data, but use the reward to figure out what should do in order to maximize the cumulative reward, and learned the policy.*

- In the Supervised Learning, the data points are assumed **i.i.d.**, while in the reinforcement learning, the data is not i.i.d., *previous output might effect the future inputs*. 
- In the Supervised Learning, *the ground truth outputs is known*, and the algorithms is trained on the known ground truth, in the RL, *the group truth is un-known*, we only know the succeeded or failed (rewards)
- In the Supervised Learning, the algorithms is trained on the **fixed dataset**, while in the RL, the algorithms is trained on the **online data** (the data is generated by the agent itself).



### Lecture 02: Supervised Learning of Behaviors
Lecture 02 covers the basics of supervised learning and how it can be used to learn behaviors in reinforcement learning. It discusses the concept of imitation learning, where an agent learns to mimic the behavior of an expert by observing its actions. The lecture also introduces the concept of behavioral cloning, where the agent learns a policy directly from the expert's actions.

## Assignments 
There are total of 5 <u>assignments</u> in this course, from imitation learning to deep Q-Learning. The assignments are designed to help you understand the concepts and algorithms in reinforcement learning, and to implement them in code.

### Assignment 01: Imitation Learning 


### Assignment 02: Policy Gradients 


